export interface DecodedApng { frames: { img: HTMLCanvasElement; delayMs: number }[]; totalMs: number; w: number; h: number; }
interface RawFrame { ctl: { w: number; h: number; x: number; y: number; dnum: number; dden: number; dispose: number; blend: number }; parts: Uint8Array[]; }

const crcTable = (() => { const table = new Uint32Array(256); for (let n = 0; n < 256; n += 1) { let crc = n; for (let bit = 0; bit < 8; bit += 1) crc = (crc & 1) ? (0xEDB88320 ^ (crc >>> 1)) : (crc >>> 1); table[n] = crc; } return table; })();
const signature = new Uint8Array([137, 80, 78, 71, 13, 10, 26, 10]);
function crc32(bytes: Uint8Array) { let crc = 0xFFFFFFFF; for (let index = 0; index < bytes.length; index += 1) crc = crcTable[(crc ^ bytes[index]) & 0xFF] ^ (crc >>> 8); return (crc ^ 0xFFFFFFFF) >>> 0; }
function chunk(type: string, data: Uint8Array) { const output = new Uint8Array(12 + data.length); const view = new DataView(output.buffer); view.setUint32(0, data.length); for (let index = 0; index < 4; index += 1) output[4 + index] = type.charCodeAt(index); output.set(data, 8); view.setUint32(8 + data.length, crc32(output.subarray(4, 8 + data.length))); return output; }

export async function decodeAPNG(buffer: ArrayBuffer, firstFrameOnly = false): Promise<DecodedApng | null> {
  const bytes = new Uint8Array(buffer); if (bytes.length < 8 || signature.some((value, index) => bytes[index] !== value)) return null;
  const view = new DataView(buffer); let position = 8; let ihdr: Uint8Array | null = null; let hasAnimation = false; let current: RawFrame | null = null; let seenIdat = false; let firstControlBeforeIdat = false; const shared: Uint8Array[] = []; const rawFrames: RawFrame[] = [];
  while (position + 8 <= bytes.length) { const length = view.getUint32(position); const type = String.fromCharCode(bytes[position + 4], bytes[position + 5], bytes[position + 6], bytes[position + 7]); const start = position + 8; const end = start + length; if (end + 4 > bytes.length) break;
    if (type === 'IHDR') ihdr = bytes.slice(start, end); else if (type === 'acTL') hasAnimation = true; else if (type === 'fcTL') { current = { ctl: { w: view.getUint32(start + 4), h: view.getUint32(start + 8), x: view.getUint32(start + 12), y: view.getUint32(start + 16), dnum: view.getUint16(start + 20), dden: view.getUint16(start + 22), dispose: bytes[start + 24], blend: bytes[start + 25] }, parts: [] }; rawFrames.push(current); if (!seenIdat) firstControlBeforeIdat = true; } else if (type === 'IDAT') { seenIdat = true; if (current && firstControlBeforeIdat) current.parts.push(bytes.slice(start, end)); } else if (type === 'fdAT' && current) current.parts.push(bytes.slice(start + 4, end)); else if (type === 'IEND') break; else if (!seenIdat) shared.push(bytes.slice(position, end + 4)); position = end + 4; }
  if (!hasAnimation || !ihdr) return null; const availableFrames = rawFrames.filter((frame) => frame.parts.length); const framesWithData = firstFrameOnly ? availableFrames.slice(0, 1) : availableFrames; if (!framesWithData.length) return null; const width = view.getUint32(16); const height = view.getUint32(20); const bitmaps: ImageBitmap[] = [];
  for (const frame of framesWithData) { const frameHeader = ihdr.slice(); const frameView = new DataView(frameHeader.buffer); frameView.setUint32(0, frame.ctl.w); frameView.setUint32(4, frame.ctl.h); const partLength = frame.parts.reduce((total, part) => total + part.length, 0); const idat = new Uint8Array(partLength); let offset = 0; for (const part of frame.parts) { idat.set(part, offset); offset += part.length; } bitmaps.push(await createImageBitmap(new Blob([signature, chunk('IHDR', frameHeader), ...shared, chunk('IDAT', idat), chunk('IEND', new Uint8Array())], { type: 'image/png' }))); }
  const composite = document.createElement('canvas'); composite.width = width; composite.height = height; const compositeContext = composite.getContext('2d')!; const frames: DecodedApng['frames'] = []; let totalMs = 0; if (framesWithData[0].ctl.dispose === 2) framesWithData[0].ctl.dispose = 1;
  for (let index = 0; index < framesWithData.length; index += 1) { const { ctl } = framesWithData[index]; const before = ctl.dispose === 2 ? compositeContext.getImageData(0, 0, width, height) : null; if (ctl.blend === 0) compositeContext.clearRect(ctl.x, ctl.y, ctl.w, ctl.h); compositeContext.drawImage(bitmaps[index], ctl.x, ctl.y); const snapshot = document.createElement('canvas'); snapshot.width = width; snapshot.height = height; snapshot.getContext('2d')!.drawImage(composite, 0, 0); const delayMs = Math.max(20, 1000 * (ctl.dnum === 0 ? .01 : ctl.dnum / (ctl.dden || 100))); frames.push({ img: snapshot, delayMs }); totalMs += delayMs; if (ctl.dispose === 1) compositeContext.clearRect(ctl.x, ctl.y, ctl.w, ctl.h); else if (ctl.dispose === 2 && before) compositeContext.putImageData(before, 0, 0); }
  bitmaps.forEach((bitmap) => bitmap.close()); return { frames, totalMs, w: width, h: height };
}

export function animFrameAt(animation: DecodedApng, milliseconds: number) { const time = ((milliseconds % animation.totalMs) + animation.totalMs) % animation.totalMs; let elapsed = 0; for (const frame of animation.frames) { elapsed += frame.delayMs; if (time < elapsed) return frame.img; } return animation.frames.at(-1)!.img; }
