const { chromium } = require('C:/Users/akiru/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const key = process.env.MITEMITE_TEST_ACCESS_KEY;
if (!key) throw new Error('Set MITEMITE_TEST_ACCESS_KEY for the authorized access test.');
const base = process.env.MITEMITE_BASE_URL || 'http://localhost:3000/linemmk/';
(async () => {
  const browser = await chromium.launch({ headless: true, executablePath: 'C:/Users/akiru/AppData/Local/ms-playwright/chromium_headless_shell-1228/chrome-headless-shell-win64/chrome-headless-shell.exe' });
  const context = await browser.newContext({ viewport: { width: 1280, height: 1000 } });
  const page = await context.newPage(); const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  page.on('response', response => { if(response.status() >= 400) errors.push(`${response.status()} ${response.url()}`); });
  const locked = async () => { await page.getByLabel('アクセスキー', { exact: true }).waitFor(); if(await page.getByRole('link', { name: '使い方', exact: true }).count()) throw new Error('App exposed before authorization'); };
  await page.goto(base); await locked();
  await page.evaluate(() => localStorage.setItem('auth_verified', 'true'));
  await page.reload(); await locked();
  await page.getByLabel('アクセスキー', { exact: true }).fill('invalid-test-key');
  await page.getByRole('button', { name: 'みてみてくんを開く', exact: true }).click();
  await page.getByRole('alert').waitFor(); await locked();
  await page.getByLabel('アクセスキー', { exact: true }).fill(key);
  await page.getByRole('button', { name: 'みてみてくんを開く', exact: true }).click();
  await page.getByRole('link', { name: '使い方', exact: true }).waitFor();
  await page.reload(); await page.getByRole('link', { name: '使い方', exact: true }).waitFor();
  await page.getByPlaceholder('メッセージを入力').fill('ガイドから戻っても残る会話');
  await page.locator('textarea').press('Enter');
  await page.getByRole('link', { name: '使い方', exact: true }).click();
  await page.getByRole('heading', { name: '5つの画面で、最初の1本。', exact: true }).waitFor();
  await page.reload(); await page.getByRole('heading', { name: '5つの画面で、最初の1本。', exact: true }).waitFor();
  await page.getByRole('link', { name: '全機能ガイド', exact: true }).click();
  await page.getByRole('heading', { name: '名前・表示の設定', exact: true }).waitFor();
  await page.getByRole('link', { name: 'アプリへ', exact: true }).click();
  await page.locator('input[type=file][accept=".png"]').first().setInputFiles(require('node:path').resolve('public/guide/03-sticker.png'));
  await page.getByPlaceholder('メッセージを入力').fill('この会話を保持'); await page.locator('textarea').press('Enter');
  await page.getByRole('link', { name: '使い方', exact: true }).click();
  await page.getByRole('heading', { name: '5つの画面で、最初の1本。', exact: true }).waitFor();
  await page.getByRole('link', { name: 'アプリへ', exact: true }).click();
  if(!await page.getByText('この会話を保持', { exact: true }).isVisible()) throw new Error('Conversation lost on guide navigation');
  if(!await page.locator('img[alt="03-sticker.png"]').isVisible()) throw new Error('Uploaded material lost on guide navigation');
  await page.goBack(); await page.getByRole('heading', { name: '5つの画面で、最初の1本。', exact: true }).waitFor();
  await page.goForward(); await page.getByRole('link', { name: '使い方', exact: true }).waitFor();
  for(const route of ['guide', 'features']) {
    const direct = await context.newPage(); await direct.goto(`${base}?${route}`);
    await direct.getByRole('heading', { name: '使い方はアプリから開けます', exact: true }).waitFor();
    if(await direct.locator('.guide-page').count()) throw new Error('Direct guide URL exposed contents');
    await direct.close();
  }
  const newContext = await browser.newContext();
  const linkPage = await newContext.newPage();
  await linkPage.goto(`${base}#access=${encodeURIComponent(key)}`);
  await linkPage.getByRole('link', { name: '使い方', exact: true }).waitFor();
  if(linkPage.url().includes('access=')) throw new Error('Access key left in URL');
  await linkPage.getByRole('link', { name: '使い方', exact: true }).click();
  await linkPage.getByRole('link', { name: '全機能ガイド', exact: true }).click();
  await linkPage.getByRole('heading', { name: '名前・表示の設定', exact: true }).waitFor();
  if(await linkPage.locator('.feature-options button').count() !== 50) throw new Error('Feature guide is incomplete');
  await linkPage.locator('#appearance .feature-options button').nth(3).click();
  await linkPage.getByRole('heading', { name: '「既読 2」の数字を変える', exact: true }).waitFor();
  await linkPage.screenshot({ path: 'output/playwright/access-guide-verified.png', fullPage: false });
  await linkPage.getByRole('link', { name: 'はじめての使い方', exact: true }).click();
  await linkPage.getByRole('heading', { name: '5つの画面で、最初の1本。', exact: true }).waitFor();
  if(await linkPage.locator('video').count() !== 5) throw new Error('Video samples are incomplete');
  for(let index = 0; index < 5; index++) {
    const video = linkPage.locator('video').nth(index);
    const result = await video.evaluate(async video => {
      video.muted = true; await video.play();
      await new Promise((resolve, reject) => { const timer = setTimeout(() => reject(new Error('Video playback timeout')), 15000); const check = () => { if(video.currentTime > .1) { clearTimeout(timer); resolve(); } else requestAnimationFrame(check); }; check(); });
      video.pause(); return { width: video.videoWidth, height: video.videoHeight, duration: video.duration };
    });
    if(!result.width || result.duration < 6) throw new Error('Video sample playback failed');
  }
  await linkPage.screenshot({ path: 'output/playwright/published-guide.png', fullPage: false });
  const freshContext = await browser.newContext(); const fresh = await freshContext.newPage();
  await fresh.goto(`${base}?guide`); await fresh.getByLabel('アクセスキー', { exact: true }).waitFor();
  await fresh.goto(`${base}#access=invalid-test-key`); await fresh.getByLabel('アクセスキー', { exact: true }).waitFor();
  await fresh.screenshot({ path: 'output/playwright/access-lock.png' });
  await fresh.setViewportSize({ width: 390, height: 844 });
  if(await fresh.evaluate(() => document.documentElement.scrollWidth > innerWidth)) throw new Error('Mobile lock-screen overflow');
  if(errors.length) throw new Error(errors.join('\n'));
  console.log('PASS: wrong key, correct key, remembered access, isolated auth, access URL cleanup, direct guide block, guide refresh/navigation, back/forward, conversation retention and mobile lock screen.');
  await browser.close();
})().catch(error => { console.error(error); process.exit(1); });
